const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(url,label)=>/^https?:\/\//.test(url??'')?`<a href="${escape(url)}" target="_blank" rel="noopener noreferrer">${escape(label)} ↗</a>`:escape(label);
const date=s=>s?new Date(s).toLocaleString('ru-RU',{timeZone:'Europe/Budapest',dateStyle:'medium',timeStyle:'short'}):'Дата не уточнена';
const names={detained:'Задержан',wanted:'Разыскивается','in-custody':'Под стражей',charged:'Предъявлено обвинение',convicted:'Осуждён',released:'Освобождён',deceased:'Погиб',injured:'Пострадал',unknown:'Неизвестно',suspect:'Подозреваемый',victim:'Потерпевший',involved:'Участник',male:'Мужчина',female:'Женщина',person:'Человек',group:'Группа',official:'Официальный источник',media:'СМИ',social:'Социальная сеть',pass:'Проверено Pro',revise:'Нужны правки',reject:'Не прошло проверку','traffic-accident':'ДТП',assault:'Нападение',fight:'Драка',robbery:'Ограбление',accident:'Несчастный случай',fire:'Пожар',rescue:'Спасательная операция','missing-person':'Пропавший человек','transport-disruption':'Транспорт',weather:'Непогода',other:'Происшествие',reported:'Сообщается',investigating:'В расследовании','suspects-detained':'Подозреваемые задержаны',resolved:'Разрешено',closed:'Закрыто',exact:'Точно',street:'Улица',district:'Район',city:'Город',hour:'До часа',day:'До дня'};
const fieldNames={title:'Заголовок',summary:'Описание события',label:'Название',note:'Примечание',description:'Описание',offense:'Правонарушение',subjectLabel:'К кому относится',condition:'Условие',text:'Текст',detail:'Подробности',caption:'Подпись',participants:'Участник',updates:'Хронология',context:'Сообщение источника',legal:'Правовая информация',media:'Фотография',location:'Место',source:'Источник'};
const labelFor=path=>path.split('.').map(p=>/^\d+$/.test(p)?Number(p)+1:fieldNames[p]??p).join(' · ');
let csrf='',selected=null,events=[],tab='preview',dirty=false,activeBusy=false,messageTimer;
function notify(text,error=false){$('#message').textContent=text;$('#message').className=error?'error':'';clearTimeout(messageTimer);messageTimer=setTimeout(()=>$('#message').textContent='',9000);}
async function api(path,body){
  const response=await fetch('/admin/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body)});
  const result=await response.json();
  if(!response.ok){if(response.status===401){$('#login').hidden=false;$('#workspace').hidden=true;$('#logout').hidden=true;}throw new Error(result.error??'Ошибка запроса');}
  return result;
}
function badge(event){const published=event.published_revision===event.revision;return `<span class="pill ${published||event.verdict==='pass'?'good':event.verdict?'warn':''}">${published?'Опубликовано':names[event.verdict]??'Ожидает проверки'}</span>`;}
function renderList(){const search=$('#search').value.toLowerCase();$('#events').innerHTML=events.filter(e=>e.title.toLowerCase().includes(search)).map(e=>`<button class="event ${selected?.id===e.id?'active':''}" data-id="${e.id}">${badge(e)}<strong>${escape(e.title)}</strong><small>${escape(date(e.occurred_at))} · v${e.revision}</small></button>`).join('')||'<p class="muted">Событий пока нет</p>';}
async function loadList(){
  const data=await api('events');events=data.events;renderList();
  $('#stats').textContent=`${events.length} событий · ${events.filter(e=>e.published_revision!==e.revision).length} версий ещё не опубликовано`;
  $('#service').innerHTML=`<p>Сегодня: ${data.usage.calls} вызовов моделей, оценка $${data.usage.usd.toFixed(3)}.</p><p>Даты на странице — по Будапешту. Поиск по интернету требует отдельно подключённого провайдера.</p>`+(data.errors.length?data.errors.map(e=>`<details><summary>${escape(e.kind)} · повтор ${escape(date(e.due_at))}</summary><pre>${escape(e.last_error)}</pre></details>`).join(''):'<p>Ошибок в очереди нет.</p>');
  $('#requests').innerHTML=data.requests.map(r=>`<div class="record"><strong>${escape(r.label)}</strong><p>${escape(r.reason)}</p><span class="muted">${escape(r.example)}</span></div>`).join('')||'<p>Модели пока не предложили новых полей.</p>';
}
function preview(){const e=selected.russian??selected.canonical;
  const profiles=e.participants.map(p=>{const f=p.profile;return `<article class="block"><div class="person-head"><h3>${escape(p.label)}</h3><span class="pill ${p.status==='detained'?'good':'warn'}">${escape(names[p.status]??p.status)}</span></div><p class="fact">${[names[p.role],names[f.gender],f.age!==undefined?`${f.age} лет`:null,f.count!==undefined?`${f.count} человек`:null,f.citizenship?.name].filter(Boolean).map(escape).join(' · ')}</p>${p.note?`<p>${escape(p.note)}</p>`:''}${p.wantedNotice?`<p>Ориентировка: ${escape(p.wantedNotice.description)}</p>`:''}<small>${link(p.sourceUrl,p.sourceLabel)} · ${escape(date(p.asOf))}</small></article>`;}).join('');
  const publicCounts=selected.published?.counts;
  return `${!selected.russian?'<div class="warning">Русского перевода ещё нет. Ниже — английский черновик.</div>':''}<p class="meta">${escape(names[e.type])} · ${escape(names[e.status])} · ${escape(e.location.label)}</p><p>${escape(e.summary)}</p>
    ${profiles?`<section class="section"><h3>Участники · ${e.participants.length}</h3>${profiles}</section>`:''}
    ${e.updates.length?`<section class="section"><h3>Хронология</h3>${e.updates.map(u=>`<div class="block"><small class="muted">${escape(date(u.publishedAt))}</small><h3>${escape(u.title)}</h3><p>${escape(u.detail)}</p>${link(u.sourceUrl,'Источник')}</div>`).join('')}</section>`:''}
    ${e.context.length?`<section class="section"><h3>Контекст и предположения</h3>${e.context.map(c=>`<div class="block"><span class="pill">${c.origin==='model'?'Предположение модели':'Сообщение источника'}</span><p>${escape(c.text)}</p>${c.evidence.map(s=>link(s.url,s.label)).join(' · ')}</div>`).join('')}</section>`:''}
    ${e.legal.length?`<section class="section"><h3>Правовая информация</h3>${e.legal.map(l=>`<div class="block"><h3>${escape(l.offense)}</h3>${l.statutes.map(s=>link(s.url,s.act+' · '+s.section)).join(' · ')}<p>${escape(l.condition)}</p><details><summary>Санкции и квалификация</summary><pre class="quote">${escape(JSON.stringify(l.penalties,null,2))}</pre></details></div>`).join('')}</section>`:''}
    ${e.media.length?`<section class="section"><h3>Фотографии</h3>${e.media.map(m=>`<div class="block">${link(m.imageUrl,m.caption)}<p class="fact">${escape(m.credit)} · права: ${escape(m.rights)}${m.isSensitive?' · чувствительное изображение':''}</p></div>`).join('')}</section>`:''}
    ${publicCounts?`<details class="section"><summary>Сейчас на сайте · сравнить перед заменой</summary><div class="block"><h3>${escape(selected.published.title)}</h3><p>${escape(selected.published.summary)}</p><p class="muted">Участников: ${publicCounts.participants} → ${e.participants.length}; фотографий: ${publicCounts.media} → ${e.media.filter(m=>['licensed','permission','public-domain'].includes(m.rights)).length}; записей хронологии: ${publicCounts.updates} → ${e.updates.length}; контекст: ${publicCounts.context} → ${e.context.length}; правовые блоки: ${publicCounts.legal} → ${e.legal.length} (после подтверждения).</p></div></details>`:''}`;
}
function sources(){return `<h3>Проверка модели</h3>${selected.quality?`<div class="block"><span class="pill ${selected.quality.payload.verdict==='pass'?'good':'warn'}">${escape(names[selected.quality.payload.verdict])}</span><p>${escape(selected.quality.payload.summary)}</p>${selected.quality.payload.issues.map(i=>`<p><strong>${escape(i.field)}</strong>: ${escape(i.reason)}${i.quote?`<span class="quote">${escape(i.quote)}</span>`:''}</p>`).join('')}<small class="muted">${escape(selected.quality.model)} · ${escape(date(selected.quality.created_at))}</small></div>`:'<p class="muted">Текущая версия ещё не проверена.</p>'}<h3>Источники · ${selected.documents.length}</h3>${selected.documents.map(d=>`<article class="block source"><span class="pill">${escape(names[d.sourceKind]??d.sourceKind)}</span><h3>${link(d.url,d.title)}</h3><small class="muted">Сохранено ${escape(date(d.fetched_at))}</small><details><summary>Прочитать сохранённый оригинал</summary><div class="quote">${escape(d.text)}</div></details><details><summary>Цитаты, использованные в карточке</summary>${selected.canonical.evidence.filter(e=>e.documentId===d.id).map(e=>`<p class="meta">${escape(labelFor(e.field))}</p><blockquote class="quote">${escape(e.quote)}</blockquote>`).join('')}</details></article>`).join('')}`;}
const options=(values,current)=>values.map(v=>`<option value="${escape(v)}" ${v===current?'selected':''}>${escape(names[v]??v)}</option>`).join('');
function editor(){const e=selected.canonical;return `<p class="muted">Правки создают новую версию. Перед публикацией она снова проходит проверку Pro.</p><form id="edit-form"><h3>Сведения о событии</h3><div class="grid2"><label>Тип<select id="edit-type">${options(['traffic-accident','assault','fight','robbery','accident','fire','rescue','missing-person','transport-disruption','weather','other'],e.type)}</select></label><label>Статус<select id="edit-status">${options(['reported','investigating','suspects-detained','wanted','resolved','closed','unknown'],e.status)}</select></label><label>Дата и время с часовым поясом<input id="edit-date" placeholder="2026-09-21T10:00:00+02:00" value="${escape(e.occurredAt??'')}"></label><label>Точность времени<select id="edit-time">${options(['exact','hour','day','unknown'],e.timePrecision)}</select></label><label>Широта<input id="latitude" type="number" step="any" min="-90" max="90" value="${escape(e.location.latitude??'')}"></label><label>Долгота<input id="longitude" type="number" step="any" min="-180" max="180" value="${escape(e.location.longitude??'')}"></label><label>Точность места<select id="edit-precision">${options(['exact','street','district','city','unknown'],e.location.precision)}</select></label></div>${selected.published?'<button type="button" id="reuse-location">Взять координаты из опубликованной карточки</button>':''}<h3 class="section">Русский текст</h3>${selected.strings?Object.entries(selected.strings).map(([path,value])=>`<label>${escape(labelFor(path))}<textarea data-path="${escape(path)}" ${path==='summary'?'class="long"':''}>${escape(value)}</textarea></label>`).join(''):'<p class="muted">После сохранения будет заказан русский перевод.</p>'}<details class="section"><summary>Английский оригинал и все поля контракта</summary><p class="muted">Расширенное редактирование. При изменении структуры сначала сохраните с новым переводом; его нужно будет проверить повторно. Общие поля из формы выше применяются поверх оригинала.</p><textarea id="canonical" class="json" spellcheck="false">${escape(JSON.stringify(e,null,2))}</textarea><label class="check"><input id="retranslate" type="checkbox">Заново перевести английский текст (заменит русский перевод в новой версии)</label></details><div class="actions footer-actions"><button class="primary" id="save">Сохранить и проверить</button><span id="dirty-label" class="meta">Изменений нет</span></div></form>`;}
function renderDetail(){if(!selected)return;const e=selected,queued=e.jobs.map(j=>`${({review:'Проверка Pro',translate:'Перевод',recheck:'Проверка источников'})[j.kind]??j.kind}: ${j.state==='running'?'выполняется':'в очереди'}`).join(' · ');
  $('#detail').innerHTML=`<div class="detail-head"><div><span class="eyebrow">СОБЫТИЕ №${e.id} · ВЕРСИЯ ${e.revision}</span><h2>${escape(e.russian?.title??e.canonical.title)}</h2><div class="meta">${escape(date(e.occurred_at))}</div></div><span class="pill ${e.published_revision===e.revision?'good':''}">${e.published_revision===e.revision?'Опубликовано':'Черновик'}</span></div>
  ${e.blockers.length?`<div class="warning">До публикации: ${e.blockers.map(escape).join(' · ')}.</div>`:'<div class="statusbox">Проверка Pro пройдена. Карточка готова к вашему решению.</div>'}
  ${queued?`<p class="meta">${escape(queued)}</p>`:''}<div class="tabs">${[['preview','Карточка'],['sources','Источники и проверка'],['edit','Редактировать']].map(([k,v])=>`<button data-tab="${k}" class="${tab===k?'active':''}">${v}</button>`).join('')}</div><div id="tab-content">${tab==='preview'?preview():tab==='sources'?sources():editor()}</div>
  <div class="actions section"><button id="publish" class="primary" ${e.blockers.length?'disabled':''}>${e.published?'Обновить на сайте':'Опубликовать'}</button><button data-job="${e.russian?'review':'translate'}">${e.russian?'Проверить Pro':'Подготовить перевод'}</button><button data-job="recheck">Проверить источники</button><button id="reload-event">Обновить карточку</button></div>`;
}
async function select(id){selected=await api('events/'+id);dirty=false;renderList();renderDetail();}
function discard(){return !dirty||window.confirm('Есть несохранённые правки. Оставить их и перейти?');}
async function ready(){const session=await api('session');csrf=session.csrf;$('#login').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;await loadList();if(events.length)await select(events[0].id);}
async function run(fn){if(activeBusy)return;activeBusy=true;try{await fn();}catch(e){notify(e.message,true);}finally{activeBusy=false;}}
$('#login-form').addEventListener('submit',e=>{e.preventDefault();run(async()=>{const s=await api('login',{token:$('#token').value});$('#token').value='';csrf=s.csrf;await ready();});});
$('#logout').onclick=()=>run(async()=>{if(!discard())return;await api('logout',{});csrf='';selected=null;dirty=false;$('#workspace').hidden=true;$('#detail').innerHTML='';$('#events').innerHTML='';$('#logout').hidden=true;$('#login').hidden=false;});
$('#search').oninput=renderList;
$('#refresh').onclick=()=>run(async()=>{if(!discard())return;await loadList();if(selected)await select(selected.id);notify('Лента обновлена');});
$('#events').onclick=e=>{const b=e.target.closest('[data-id]');if(b)run(async()=>{if(discard()){tab='preview';await select(Number(b.dataset.id));}});};
$('#detail').addEventListener('input',e=>{if(e.target.closest('#edit-form')){dirty=true;$('#dirty-label').textContent='Есть несохранённые правки';$('#publish').disabled=true;}});
$('#detail').addEventListener('click',e=>run(async()=>{
  const b=e.target.closest('button');if(!b||b.id==='save')return;
  if(b.dataset.tab){if(!discard())return;dirty=false;tab=b.dataset.tab;renderDetail();}
  if(b.id==='reload-event'){if(discard())await select(selected.id);}
  if(b.dataset.job){if(dirty)throw new Error('Сначала сохраните правки');await api(`events/${selected.id}/${b.dataset.job}`,{revision:selected.revision});await select(selected.id);notify('Задание поставлено в очередь. Результат появится после обновления карточки.');}
  if(b.id==='reuse-location'){$('#latitude').value=selected.published.latitude;$('#longitude').value=selected.published.longitude;dirty=true;$('#dirty-label').textContent='Координаты добавлены — сохраните изменения';$('#publish').disabled=true;}
  if(b.id==='publish'){$('#context-approval').checked=false;$('#legal-approval').checked=false;$('#publish-summary').textContent=`${selected.russian.title} · версия ${selected.revision}. Контекст: ${selected.russian.context.length}; правовых блоков: ${selected.russian.legal.length}.`;$('#confirmation').showModal();}
}));
$('#detail').addEventListener('submit',e=>{if(e.target.id!=='edit-form')return;e.preventDefault();run(async()=>{
  const canonical=JSON.parse($('#canonical').value);canonical.type=$('#edit-type').value;canonical.status=$('#edit-status').value;canonical.occurredAt=$('#edit-date').value.trim()||null;canonical.timePrecision=$('#edit-time').value;canonical.location.precision=$('#edit-precision').value;
  for(const key of ['latitude','longitude']){const value=$('#'+key).value;if(value==='')delete canonical.location[key];else canonical.location[key]=Number(value);}
  const strings=selected.strings&&!$('#retranslate').checked?Object.fromEntries([...document.querySelectorAll('[data-path]')].map(t=>[t.dataset.path,t.value])):null;
  await api(`events/${selected.id}/save`,{revision:selected.revision,canonical,strings});dirty=false;tab='preview';await select(selected.id);await loadList();notify('Сохранена новая версия. Проверка поставлена в очередь.');
});});
$('#cancel-publish').onclick=()=>$('#confirmation').close();
$('#confirm-publish').onclick=()=>run(async()=>{const b=$('#confirm-publish');b.disabled=true;try{await api(`events/${selected.id}/publish`,{revision:selected.revision,approvalToken:selected.approvalToken,confirm:true,includeContext:$('#context-approval').checked,includeLegal:$('#legal-approval').checked});$('#confirmation').close();await select(selected.id);await loadList();notify('Версия опубликована на сайте');}finally{b.disabled=false;}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
async function bootstrap(){
  const token=new URLSearchParams(window.location.hash.slice(1)).get('token');
  if(token){
    // Fragments are never sent in HTTP requests. Remove the credential before loading event data.
    window.history.replaceState(null,'',window.location.pathname+window.location.search);
    const session=await api('login',{token});csrf=session.csrf;
  }
  await ready();
}
const boot=()=>bootstrap().catch(e=>{if(!$('#login').hidden){if(!e.message.includes('Войдите'))notify(e.message,true);return;}notify(e.message,true);});
window.addEventListener('hashchange',()=>{if(window.location.hash.startsWith('#token='))boot();});
boot();
