export const interestReasons={
  duplicate:'Дубликат',
  animals:'Происшествие с животными',
  'industrial-disaster':'Промышленная / химическая авария',
  drugs:'Наркотики',
  'police-routine':'Рейд / полицейская рутина',
  'economic-case':'Экономическое дело',
  'extreme-activity':'Экстремальное занятие',
  'property-only':'Имущество без угрозы людям',
  'minor-consequences':'Незначительные последствия',
  'no-serious-injuries':'Нет тяжёлых пострадавших',
  'routine-transport':'Обычная транспортная новость',
  'ordinary-fire':'Обычный пожар без значимых последствий',
  'outside-topic':'Не наша тематика',
  'outside-area':'Вне нужной территории',
  'insufficient-facts':'Слишком мало достоверных сведений',
  'not-relevant':'Потеряло актуальность',
  'personal-choice':'Просто не хочу публиковать',
  other:'Другая причина',
};
